In [2]:
from scipy import stats
import numpy as np
import pandas as pd
from sklearn import model_selection
from statsmodels.stats import weightstats 
from scipy import stats as sts
from sklearn.linear_model import LogisticRegression as LR

## #3

In [5]:
n1 = 34
n2 = 16
p1 = 10 / n1
p2 = 4 / n2

P = (p1 * n1 + p2 * n2) / (n1 + n2)
Z = (p1 - p2) / np.sqrt((P * (1 - P) * (1 / n1 + 1 / n2)))

p_value = (1 - stats.norm.cdf(Z))
np.round(p_value, 4)


0.3729

## #4

In [6]:
data = pd.read_csv('banknotes.txt', header = 0, sep = '\t')
y = data[['real']]
X = data.drop(['real'], axis = 1)

In [7]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X.values, y.values, test_size = 0.25, random_state = 1)

In [8]:
y_train = np.ravel(y_train)
y_test = np.ravel(y_test)

lr1 = LR(solver = 'liblinear', random_state = 1).fit(X_train[:, 0:3], y_train)
lr2 = LR(solver = 'liblinear', random_state = 1).fit(X_train[:, 3:6], y_train)

y_123 = lr1.predict(X_test[:, 0:3])
y_456 = lr2.predict(X_test[:, 3:6])

p_123 = lr1.score(X_test[:, 0:3], y_test)
p_456 = lr2.score(X_test[:, 3:6], y_test)

print('score with features 1, 2, 3 = %f' %p_123)
print('score with features 4, 5, 6 = %f' %p_456)

score with features 1, 2, 3 = 0.800000
score with features 4, 5, 6 = 0.980000


In [32]:
res_123 = np.array([int(x1 != x2) for x1, x2 in zip(y_123, y_test)])
res_456 = np.array([int(x1 != x2) for x1, x2 in zip(y_456, y_test)])
print(y_test[:20], y_123[:20], res_123[:20], y_456[:20], res_456[:20], sep = '\n')
print(res_123.mean(), res_456.mean())


[1 1 1 0 0 0 1 1 1 0 0 1 1 1 0 0 0 1 0 1]
[1 1 1 0 0 0 1 1 1 1 0 1 1 1 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0]
[1 1 1 0 0 0 1 1 1 0 0 1 1 1 1 0 0 1 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
0.2 0.02


In [41]:
n = len(res_123)

f = sum([1 if (x1 == 1 and x2 == 0) else 0 for x1, x2 in zip(res_123, res_456)])
g = sum([1 if (x1 == 0 and x2 == 1) else 0 for x1, x2 in zip(res_123, res_456)])

print(f/n, g/n)

Z = (f - g) / np.sqrt(f + g + ((f - g) ** 2) / n)
p_value = (1 - sts.norm.cdf(Z))
p_value


0.2 0.02


0.005647246137813866

# #5

In [36]:
z = sts.norm.ppf(0.975)

left_boundary = (f - g) / n - z * np.sqrt(float((f + g)) / n**2 - float((f - g)**2) / n**3)
right_boundary = (f - g) / n + z * np.sqrt(float((f + g)) / n**2 - float((f - g)**2) / n**3)

print("score_456 - score_123 = %f" %((f - g) / n))
print("95%% confidence interval for score_456 - score_123: [%f, %f]" %(left_boundary, right_boundary))
print(np.round(left_boundary, 4))



score_456 - score_123 = 0.180000
95% confidence interval for score_456 - score_123: [0.059945, 0.300055]
0.0599


# #6

In [12]:
n1 = 200000
n2 = 100
p1 = 525
p2 = 541.4
sigma = 100

Z1 = (p2 - p1) / (sigma / n2 ** 0.5)
p_value1 = 1 - sts.norm.cdf(Z1)
np.round(p_value1, 4)

0.0505

# #7

In [13]:
n1 = 200000
n2 = 100
p1 = 525
p2 = 541.5
sigma = 100

Z2 = (p2 - p1) / (sigma / n2 ** 0.5)
p_value2 = 1 - sts.norm.cdf(Z2)
np.round(p_value2, 4)

0.0495